/**
 * Post-processes the static web export (`dist/`) into an installable,
 * offline-capable PWA for GitHub Pages:
 *
 *  - writes `sw.js`, a service worker that precaches every exported file
 *    under its clean URL (GitHub Pages serves /play/x from /play/x.html);
 *  - copies `+not-found.html` to `404.html`, which GitHub Pages serves for
 *    unknown paths (and the worker uses as its offline fallback);
 *  - adds `.nojekyll`, needed only if the site is ever published from a branch
 *    (Jekyll would hide `_expo/`); the Actions deploy does not run Jekyll.
 *
 * Run after `expo export -p web`, with the same BASE_URL.
 */
import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const DIST = join(process.cwd(), 'dist');
const BASE = (process.env.BASE_URL ?? '').replace(/\/+$/, '');

/** Files that are never worth precaching. */
const SKIP = [
  /^sw\.js$/,
  /^_sitemap\.html$/,
  /\[.+\]\.html$/,
  /\.map$/,
  /^_expo\/\.routes\.json$/,
  // Same content as 404.html, which is precached instead (served for unknown paths).
  /^\+not-found\.html$/,
];

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

/** URL the browser will request for an exported file. */
function urlFor(file: string): string {
  const path = relative(DIST, file).split(sep).join('/');
  if (path === 'index.html') return `${BASE}/`;
  if (path.endsWith('/index.html')) return `${BASE}/${path.slice(0, -'index.html'.length)}`;
  if (path.endsWith('.html')) return `${BASE}/${path.slice(0, -'.html'.length)}`;
  return `${BASE}/${path}`;
}

function main(): void {
  if (!existsSync(join(DIST, 'index.html'))) {
    throw new Error('dist/index.html not found: run `expo export -p web` first');
  }

  const notFound = join(DIST, '+not-found.html');
  if (existsSync(notFound)) copyFileSync(notFound, join(DIST, '404.html'));
  writeFileSync(join(DIST, '.nojekyll'), '');

  const files = walk(DIST)
    .filter((file) => !file.endsWith(`${sep}.nojekyll`))
    .filter((file) => !SKIP.some((re) => re.test(relative(DIST, file).split(sep).join('/'))))
    .sort();

  const hash = createHash('sha256');
  const entries = files.map((file) => {
    hash.update(relative(DIST, file));
    hash.update(readFileSync(file));
    // Fetch the real file, store it under the URL the page will ask for.
    return { url: urlFor(file), file: `${BASE}/${relative(DIST, file).split(sep).join('/')}` };
  });
  const version = hash.digest('hex').slice(0, 12);

  writeFileSync(join(DIST, 'sw.js'), serviceWorkerSource(version, entries));
  const kb = Math.round(files.reduce((n, f) => n + statSync(f).size, 0) / 1024);
  console.log(
    `✓ sw.js: ${entries.length} files (${kb} KB) precached, version ${version}, base "${BASE || '/'}"`,
  );
}

function serviceWorkerSource(version: string, entries: readonly { url: string; file: string }[]): string {
  return `// Generated by scripts/build-pwa.ts. Do not edit.
const VERSION = '${version}';
const CACHE = 'dominosa-' + VERSION;
const BASE = ${JSON.stringify(BASE)};
const PRECACHE = ${JSON.stringify(entries)};
const NAVIGATION_TIMEOUT_MS = 3000;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      Promise.all(
        PRECACHE.map(({ url, file }) =>
          // The query string skips any CDN copy from before this deploy.
          fetch(file + '?v=' + VERSION, { cache: 'no-cache' }).then((res) => {
            if (!res.ok) throw new Error('Precache failed: ' + file);
            return cache.put(url, res);
          }),
        ),
      ),
    ).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('dominosa-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

/** Cache key for a page URL: /base/, /base/play/x (no .html, no trailing slash). */
function pageKey(pathname) {
  let key = pathname.replace(/\\.html$/, '');
  if (key.endsWith('/index')) key = key.slice(0, -'index'.length);
  if (key.length > BASE.length + 1 && key.endsWith('/')) key = key.slice(0, -1);
  return key;
}

function put(key, res) {
  if (!res.ok || res.redirected || res.type !== 'basic') return;
  const copy = res.clone();
  caches.open(CACHE).then((cache) => cache.put(key, copy));
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(BASE + '/')) return;

  if (request.mode === 'navigate') {
    // Network first so a new deploy shows up, but never wait more than a few
    // seconds on a bad connection when the page is already cached.
    const key = pageKey(url.pathname);
    const network = fetch(request).then((res) => {
      put(key, res);
      return res;
    });
    event.waitUntil(network.catch(() => undefined));
    const timeout = new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), NAVIGATION_TIMEOUT_MS));
    event.respondWith(
      Promise.race([network, timeout])
        .catch(() => caches.match(key).then((hit) => hit || network))
        .catch(() => caches.match(BASE + '/404').then((hit) => hit || caches.match(BASE + '/'))),
    );
    return;
  }

  // Assets are content-hashed or static: cache first, and keep anything new
  // (e.g. the bundle of a page served by an older worker) for offline use.
  event.respondWith(
    caches.match(url.pathname).then(
      (hit) =>
        hit ||
        fetch(request).then((res) => {
          put(url.pathname, res);
          return res;
        }),
    ),
  );
});
`;
}

main();
